name: with every branch

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: git branch
      - run: |
          echo "##[set-output name=branch;]$(
           echo "${{ github.event.ref }}" | awk -F "/" '{ print $(NF) }'
          )"
        id: branch
      - name: use output of previous step
        run: echo "${{ steps.branch.outputs.branch }}"
