name: node

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  sandbox:
    strategy:
      matrix:
        target:
          - hoge
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: node -v
    - run: git checkout "fuga-${{matrix.target}}" || git checkout -b "fuga-${{ matrix.target }}"
    - run: touch test.txt
    - run: |
        if [[ -n "$(git status --porcelain .)" ]]; then
          git config user.name okitan # why global needed
          git config user.email okitakunio@gmail.com

          git add -A .
          git commit -m "add test.txt"
          
          # git remote set-url origin "https:/okitan:${{ secrets.GITHUB_TOKEN }}@github.com/okitan/actions-sandbox.git"
          
          git push origin "fuga-${{ matrix.target}}"
        fi
