name: sandbox

on:
  repository_dispatch:
    types: [sandbox]
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  sandbox:
    strategy:
      matrix:
        target:
          - hoge
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: git branch --remote | xargs -I {} -n echo "branch: {}"
    - run: git switch "fuga-${{matrix.target}}" || git switch --orphan "fuga-${{ matrix.target }}"
    - run: touch test.txt
    - run: |
        if [[ -n "$(git status --porcelain .)" ]]; then
          git config user.name okitan
          git config user.email okitakunio@gmail.com

          git add -A .
          git commit -m "add test.txt"
          
          git remote set-url origin "https://okitan:${{ secrets.GITHUB_TOKEN }}@github.com/okitan/actions-sandbox.git"
          
          git push origin "fuga-${{ matrix.target}}"
        fi
